version: 2
jobs:
  build:
    working_directory: ~/python-echoprint
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox
      - run:
          name: running tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            tox


branches:
  only:
    - py3-compat
